version: "3.9"

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    mem_limit: 512M
    memswap_limit: 512M
    mem_swappiness: 0
    command:  redis-server --maxmemory 512mb --maxmemorypolicy allkeys-1ru

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 2G
    mem_limit: 3G
    mem_swappiness: 0
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 4G
    mem_limit: 6G
    memswap_limit: 7G
    mem_swappiness: 0

volumes:
  data:
  media:
    driver: rclone
    driver_opts:
      remote: "onedrive:paperless/media"
      allow_other: "true"
      vfs_cache_mode: "full"
      poll_interval: 0
  export:
    driver: rclone
    driver_opts:
      remote: "onedrive:paperless/export"
      allow_other: "true"
      vfs_cache_mode: "full"
      poll_interval: 0
  consume:
    driver: rclone
    driver_opts:
      remote: "onedrive:paperless/consume"
      allow_other: "true"
      vfs_cache_mode: "full"
      poll_interval: 0
  pgdata:
  redisdata:
