version: "3"

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - onedrive/data:/usr/src/paperless/data
      - onedrive/media:/usr/src/paperless/media
      - onedrive/export:/usr/src/paperless/export
      - onedrive/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    env_file:
      - stack.env

volumes:
  onedrive:
    driver: rclone
    driver_opts:
      remote: "onedrive:paperless"
      allow_other: "true"
      vfs_cache_mode: "full"
      poll_interval: 0
  data:
  media:
  pgdata:
  redisdata:
